version: '3'
services:
  users_server:
    image: golang:alpine3.15
    command: go run usersServer.go
    volumes:
      - $PWD:/usr/src/myapp
    working_dir: /usr/src/myapp/users/server
  orders_server:
    image: golang:alpine3.15
    command: go run ordersServer.go
    volumes:
      - $PWD:/usr/src/myapp
    working_dir: /usr/src/myapp/orders/server
  goods_server:
    image: golang:alpine3.15
    command: go run goodsServer.go
    volumes:
      - $PWD:/usr/src/myapp
    working_dir: /usr/src/myapp/goods/server
  ltstcc:
    image: golang:alpine3.15
    command: go run main.go
    volumes:
      - $PWD:/usr/src/myapp
    working_dir: /usr/src/myapp
    ports:
      - "8000:8000"
    depends_on:
      - users_server
      - goods_server
      - orders_server
