// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: goods/goods.proto

package goods

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoodsInfoClient is the client API for GoodsInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsInfoClient interface {
	//获取商品信息
	GetGoodsInfo(ctx context.Context, in *GoodsId, opts ...grpc.CallOption) (*Goods, error)
	//冻结商品数量
	GoodsFrozen(ctx context.Context, in *GoodsFrozenParams, opts ...grpc.CallOption) (*GoodsFrozenResp, error)
	//冻结商品数量取消
	GoodsFrozenCancel(ctx context.Context, in *GoodsFrozenCancelParams, opts ...grpc.CallOption) (*GoodsSuccess, error)
	AutoMigrate(ctx context.Context, in *GoodsId, opts ...grpc.CallOption) (*GoodsSuccess, error)
}

type goodsInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsInfoClient(cc grpc.ClientConnInterface) GoodsInfoClient {
	return &goodsInfoClient{cc}
}

func (c *goodsInfoClient) GetGoodsInfo(ctx context.Context, in *GoodsId, opts ...grpc.CallOption) (*Goods, error) {
	out := new(Goods)
	err := c.cc.Invoke(ctx, "/GoodsInfo/getGoodsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) GoodsFrozen(ctx context.Context, in *GoodsFrozenParams, opts ...grpc.CallOption) (*GoodsFrozenResp, error) {
	out := new(GoodsFrozenResp)
	err := c.cc.Invoke(ctx, "/GoodsInfo/goodsFrozen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) GoodsFrozenCancel(ctx context.Context, in *GoodsFrozenCancelParams, opts ...grpc.CallOption) (*GoodsSuccess, error) {
	out := new(GoodsSuccess)
	err := c.cc.Invoke(ctx, "/GoodsInfo/goodsFrozenCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) AutoMigrate(ctx context.Context, in *GoodsId, opts ...grpc.CallOption) (*GoodsSuccess, error) {
	out := new(GoodsSuccess)
	err := c.cc.Invoke(ctx, "/GoodsInfo/autoMigrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsInfoServer is the server API for GoodsInfo service.
// All implementations must embed UnimplementedGoodsInfoServer
// for forward compatibility
type GoodsInfoServer interface {
	//获取商品信息
	GetGoodsInfo(context.Context, *GoodsId) (*Goods, error)
	//冻结商品数量
	GoodsFrozen(context.Context, *GoodsFrozenParams) (*GoodsFrozenResp, error)
	//冻结商品数量取消
	GoodsFrozenCancel(context.Context, *GoodsFrozenCancelParams) (*GoodsSuccess, error)
	AutoMigrate(context.Context, *GoodsId) (*GoodsSuccess, error)
	mustEmbedUnimplementedGoodsInfoServer()
}

// UnimplementedGoodsInfoServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsInfoServer struct {
}

func (UnimplementedGoodsInfoServer) GetGoodsInfo(context.Context, *GoodsId) (*Goods, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsInfo not implemented")
}
func (UnimplementedGoodsInfoServer) GoodsFrozen(context.Context, *GoodsFrozenParams) (*GoodsFrozenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodsFrozen not implemented")
}
func (UnimplementedGoodsInfoServer) GoodsFrozenCancel(context.Context, *GoodsFrozenCancelParams) (*GoodsSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodsFrozenCancel not implemented")
}
func (UnimplementedGoodsInfoServer) AutoMigrate(context.Context, *GoodsId) (*GoodsSuccess, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoMigrate not implemented")
}
func (UnimplementedGoodsInfoServer) mustEmbedUnimplementedGoodsInfoServer() {}

// UnsafeGoodsInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsInfoServer will
// result in compilation errors.
type UnsafeGoodsInfoServer interface {
	mustEmbedUnimplementedGoodsInfoServer()
}

func RegisterGoodsInfoServer(s grpc.ServiceRegistrar, srv GoodsInfoServer) {
	s.RegisterService(&GoodsInfo_ServiceDesc, srv)
}

func _GoodsInfo_GetGoodsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).GetGoodsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoodsInfo/getGoodsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).GetGoodsInfo(ctx, req.(*GoodsId))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_GoodsFrozen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsFrozenParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).GoodsFrozen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoodsInfo/goodsFrozen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).GoodsFrozen(ctx, req.(*GoodsFrozenParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_GoodsFrozenCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsFrozenCancelParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).GoodsFrozenCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoodsInfo/goodsFrozenCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).GoodsFrozenCancel(ctx, req.(*GoodsFrozenCancelParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_AutoMigrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).AutoMigrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoodsInfo/autoMigrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).AutoMigrate(ctx, req.(*GoodsId))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsInfo_ServiceDesc is the grpc.ServiceDesc for GoodsInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GoodsInfo",
	HandlerType: (*GoodsInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getGoodsInfo",
			Handler:    _GoodsInfo_GetGoodsInfo_Handler,
		},
		{
			MethodName: "goodsFrozen",
			Handler:    _GoodsInfo_GoodsFrozen_Handler,
		},
		{
			MethodName: "goodsFrozenCancel",
			Handler:    _GoodsInfo_GoodsFrozenCancel_Handler,
		},
		{
			MethodName: "autoMigrate",
			Handler:    _GoodsInfo_AutoMigrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods/goods.proto",
}
